### ISSUE TITLE
Als gebruiker kan ik gebruik maken van een gebruiksvriendelijke UI

### ISSUE THREAD

**Issue by Djennik** [OpenSkool/OpenSkool#11]

**Comment by Moeriki** [comment]
We need an existing design library to minimise the work needed on UI development.

We're looking for something with the following features.

### Required

- Accessibility
- Internationalisation
- Tree-shakeable

### Recommended

- Dark Mode
- Minimal design
- Customisable

## References

- https://xd.adobe.com/view/0b106722-7ce6-4edf-aabe-cba4dff72867-5e43/

## Options

- ⚪️ Unknown
- 🟣 Should be tested
- 🟢 Good
- 🟡 Ok
- 🟠 Average
- 🔴 Bad

| Name | ⬇️ |✨ | ♿️ | 💄 | 🌴 | 📝 |
| --- | --- | --- | --- | --- | --- | --- |
| Quasar | 53k | 19.7k | 🟡 | 🟢 | 🟣 | Material design. |
| Element UI | 250k | 51.2k | 🟠 | 🟢 | 🟣 |
| PrimeVue | 22.5k | 1.8k | 🟠 | 🟣 | 🟣 |
| Bootstrap v5 | 309k | 154k | 🟢 | 🟢 | 🟢 | No Vue components. |



## Nope

- Buefy: Not Vue 3 ready. Would be 🟠 otherwise.
- Chakra UI: Not Vue 3 ready. Would be 🟢 otherwise.
- Oruga UI: Accessibility is 🔴. Would be 🟡 otherwise.
- Vuetify: Not Vue 3 ready. Would be 🟡 otherwise.
- Vue-Bootstrap: Not Vue 3 ready. Still on Bootstrap 4.
